services:
  electricity:
    image: ghcr.io/tuomaz/electricity:latest
    restart: always
    environment:
      ID: "your_id_here"
      HATOKEN: "your_ha_token_here"
      HAURI: "your_ha_uri_here"
      AREA: "SE2"
      DAWN: "number.dawn_maximum_current"
      DAWN_SWITCH: "switch.dawn_charging"
      DAWN_CURRENT: "sensor.dawn_actual_current"
      PV_ONLY_SWITCH: "input_boolean.pv_only_charging"
      NOTIFY_DEVICE: "mobile_app_your_device"
      PHASE_1_CURRENT: "sensor.current_phase_1"
      PHASE_2_CURRENT: "sensor.current_phase_2"
      PHASE_3_CURRENT: "sensor.current_phase_3"
      PHASE_1_EXPORT: "sensor.momentary_active_export_phase_1"
      PHASE_2_EXPORT: "sensor.momentary_active_export_phase_2"
      PHASE_3_EXPORT: "sensor.momentary_active_export_phase_3"
      PHASE_1_IMPORT: "sensor.momentary_active_import_phase_1"
      PHASE_2_IMPORT: "sensor.momentary_active_import_phase_2"
      PHASE_3_IMPORT: "sensor.momentary_active_import_phase_3"
      PHASE_1_VOLTAGE: "sensor.voltage_phase_1"
      PHASE_2_VOLTAGE: "sensor.voltage_phase_2"
      PHASE_3_VOLTAGE: "sensor.voltage_phase_3"
